### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jorgeorpinel**
Accompanying changes to GS work in https://github.com/iterative/mlem.ai/pull/199.

---

- [ ] See also (finish) https://github.com/iterative/example-gto/pull/15

### CODE REVIEW

**Comment by aguschin** [comment]
Inspired by your changes, I tried to make that even shorter https://github.com/aguschin/example-gto

**Comment by aguschin** [comment]
WDYT?

**Comment by jorgeorpinel** [comment]
@aguschin I like it. The installation part may be desirable still.

Feel free to close this PR if you prefer. Too bad my commits won't make it to the `main` history though 🙁 -- could update this one if you choose to keep some installation instructions.

Up to you

**Comment by aguschin** [comment]
This repo is automatically generated, so to include your commits to the history, you need to make a PR to example-repos-dev)

**Comment by jorgeorpinel** [comment]
Will we end up adding some more Installation info? Closing for now.

**Pull request closed without merging**
